from aiogram.dispatcher.filters.state import StatesGroup, State

class CheckState(StatesGroup):
    waiting_for_after_begining = State()
    waiting_for_put_vuz_in_mem = State()
    waiting_for_offer_subj = State()
    waiting_for_select_subj = State()
    waiting_for_select_criterion0 = State()
    waiting_for_select_criterion1 = State()
    waiting_for_select_criterion2 = State()
    waiting_for_select_criterion3 = State()
    waiting_for_select_criterion4 = State()
    waiting_for_select_criterion5 = State()
    waiting_for_select_criterion6 = State()
    waiting_for_select_criterion7 = State()
    waiting_for_select_criterion8 = State()
    waiting_for_select_criterion9 = State()
    waiting_for_select_criterion10 = State()
    waiting_for_select_criterion11 = State()
    waiting_for_select_criterion12 = State()
    waiting_for_select_criterion13 = State()
    waiting_for_select_criterion14 = State()
    waiting_for_select_criterion15 = State()
    waiting_for_select_criterion16 = State()
    waiting_for_select_criterion17 = State()
    waiting_for_select_criterion18 = State()
    waiting_for_selected_criterion = State()
    waiting_for_top = State()
    waiting_for_selected_top = State()
    waiting_for_show_rating = State()
    waiting_for_additional_info = State()
    waiting_for_additional_info_ = State()
    waiting_for_the_end = State()

    waiting_for_message_from_admin = State()
    waiting_for_look_base_ = State()